### ISSUE TITLE
Not currently working

### ISSUE THREAD

**Issue by duanefields** [Recognition101/bluebird-dash-docs#1]
Just a heads up that it generates an empty docset currently. It seems to download the HTML fine, but that's as far as I got in debugging.

**Comment by timhuff** [comment]
I was just attempting to add this to my Dash as well. It was a bummer to find it not working - would love to have bluebird docs in there.

**Comment by Codelica** [comment]
I think the doc formatting has changed a bit since he published this.  I left a pull request w/ a little correction and icon addition.  If you're impatient, you'll find it in my fork:

https://github.com/Codelica/bluebird-dash-docs

**Comment by duanefields** [comment]
Got it, thanks Jakes

> On Dec 17, 2014, at 5:37 PM, James notifications@github.com wrote:
> 
> I think the doc formatting has changed a bit since he published this. I left a pull request w/ a little correction and icon addition. If you're impatient, you'll find it in my fork:
> 
> https://github.com/Codelica/bluebird-dash-docs https://github.com/Codelica/bluebird-dash-docs
> —
> Reply to this email directly or view it on GitHub https://github.com/Recognition101/bluebird-dash-docs/issues/1#issuecomment-67417572.

## 

Duane Fields
duane@duanefields.com

**Comment by Recognition101** [comment]
Fixed with #2, thanks @Codelica!
