### ISSUE TITLE
New Bluebird.js docs

### ISSUE THREAD

**Issue by JasonMore** [Recognition101/bluebird-dash-docs#3]
Any chance you were planning to upgrade this to the new version/docs site of bluebird?

**Comment by Recognition101** [comment]
I just made a new version that pulls the docs from [here](http://bluebirdjs.com/docs/api-reference.html). Is that the new site you were talking about? Try it out and let me know if it works for you!

**Comment by JasonMore** [comment]
@Recognition101 works great thanks!
